### ISSUE TITLE
Upgrade checkout and setup-python actions in workflow

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#763]
New versions of checkout and setup-python actions are available:
- https://github.com/actions/checkout (actions/checkout@v3)
- https://github.com/actions/setup-python (actions/setup-python@v4)

The last one comes with an easy way to use cache:
e.g
```
- name: Set up python ${{ matrix.python }}
  uses: actions/setup-python@v4
  with:
    python-version: ${{ matrix.python }}
    cache: 'poetry'
```
Could be worth to use them in the workflow
