### ISSUE TITLE
Use PyPis Trusted Publisher Management for releases

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaerocom#972]
Publish to pypi uses currently the token based publishing code at:
https://github.com/metno/pyaerocom/blob/main-dev/.github/workflows/publish.yml

Tokens can be stolen and thus the code at pypi can be modified without recognition. PyPi and github prefer therefore PyPis Trusted Publisher Management.

Steps required:
In publish.yml:
add after `runs-on: ubuntu-latest`
```yml
    environment: release
    permissions:
      id-token: write
```
remove
```yml
  with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
```

In github:
  * remove secret PYPI_API_TOKEN
  * add `release` environment

In pypi:
  * remove api-tokens under Account Settings
  * under Projects -> pyaercom -> Publishing: Add new publisher (the github-repo, release env, and publish.yml)
